### PR TITLE
Fixes and instructions for CrunchFlow chemistry engine.

### LINKED ISSUE #5: CrunchFlow engine needs to be tested
We haven't tested the building and running of the CrunchFlow engine using the new CMake build system now in the master branch. We should do this.

### PR DESCRIPTION
**Pull request by jnjohnsonlbl**
* CrunchFlow has now been successfully tested (in the same sense as PFlotran).
* Added CrunchFlow library build instructions.
* Formalizes a naming scheme for chemistry benchmarks.

Fixes #5

### CODE REVIEW

**Comment by jnjohnsonlbl** [comment]
Running tests...
Test project /Users/jeff/projects/alquimia-dev/build
      Start  1: test_alquimia_c_utils_exe
 1/24 Test  #1: test_alquimia_c_utils_exe ............   Passed    0.01 sec
      Start  2: calcite_short_ac_pflotran
 2/24 Test  #2: calcite_short_ac_pflotran ............   Passed    0.06 sec
      Start  3: calcite_short_pc_pflotran
 3/24 Test  #3: calcite_short_pc_pflotran ............   Passed    0.06 sec
      Start  4: calcite_vf_pc_pflotran
 4/24 Test  #4: calcite_vf_pc_pflotran ...............   Passed    0.06 sec
      Start  5: general_reaction_ac_pflotran
 5/24 Test  #5: general_reaction_ac_pflotran .........   Passed    0.06 sec
      Start  6: general_reaction_pc_pflotran
 6/24 Test  #6: general_reaction_pc_pflotran .........   Passed    0.06 sec
      Start  7: ion_exchange_valocchi_ac_pflotran
 7/24 Test  #7: ion_exchange_valocchi_ac_pflotran ....   Passed    0.06 sec
      Start  8: ion_exchange_valocchi_pc_pflotran
 8/24 Test  #8: ion_exchange_valocchi_pc_pflotran ....   Passed    0.06 sec
      Start  9: isotherms_ac_pflotran
 9/24 Test  #9: isotherms_ac_pflotran ................   Passed    0.06 sec
      Start 10: isotherms_pc_pflotran
10/24 Test #10: isotherms_pc_pflotran ................   Passed    0.06 sec
      Start 11: surface_complexation_2_ac_pflotran
11/24 Test #11: surface_complexation_2_ac_pflotran ...   Passed    0.06 sec
      Start 12: surface_complexation_2_pc_pflotran
12/24 Test #12: surface_complexation_2_pc_pflotran ...   Passed    0.06 sec
      Start 13: calcite_short_ac_crunch
13/24 Test #13: calcite_short_ac_crunch ..............   Passed    0.40 sec
      Start 14: calcite_short_cc_crunch
14/24 Test #14: calcite_short_cc_crunch ..............   Passed    0.40 sec
      Start 15: calcite_vf_ac_crunch
15/24 Test #15: calcite_vf_ac_crunch .................   Passed    0.40 sec
      Start 16: calcite_vf_cc_crunch
16/24 Test #16: calcite_vf_cc_crunch .................   Passed    0.40 sec
      Start 17: general_reaction_ac_crunch
17/24 Test #17: general_reaction_ac_crunch ...........   Passed    0.39 sec
      Start 18: general_reaction_cc_crunch
18/24 Test #18: general_reaction_cc_crunch ...........   Passed    0.39 sec
      Start 19: ion_exchange_valocchi_ac_crunch
19/24 Test #19: ion_exchange_valocchi_ac_crunch ......   Passed    0.38 sec
      Start 20: ion_exchange_valocchi_cc_crunch
20/24 Test #20: ion_exchange_valocchi_cc_crunch ......   Passed    0.39 sec
      Start 21: isotherms_ac_crunch
21/24 Test #21: isotherms_ac_crunch ..................   Passed    0.39 sec
      Start 22: isotherms_cc_crunch
22/24 Test #22: isotherms_cc_crunch ..................   Passed    0.39 sec
      Start 23: surface_complexation_2_ac_crunch
23/24 Test #23: surface_complexation_2_ac_crunch .....   Passed    0.40 sec
      Start 24: surface_complexation_2_cc_crunch
24/24 Test #24: surface_complexation_2_cc_crunch .....   Passed    0.39 sec

**Comment by smolins** [comment]
I get an error in the make step:

[ 50%] Building C object alquimia/CMakeFiles/alquimia.dir/alquimia_util.c.o
/media/data2/smolins/test1/alquimia-dev/alquimia/alquimia_util.c: In function ‘CopyAlquimiaVectorString’:
/media/data2/smolins/test1/alquimia-dev/alquimia/alquimia_util.c:119:5: error: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration]
     destination->data[i] = strdup(source->data[i]);
     ^
/media/data2/smolins/test1/alquimia-dev/alquimia/alquimia_util.c:119:26: error: assignment makes pointer from integer without a cast
     destination->data[i] = strdup(source->data[i]);
                          ^
/media/data2/smolins/test1/alquimia-dev/alquimia/alquimia_util.c: In function ‘CopyAlquimiaGeochemicalCondition’:
/media/data2/smolins/test1/alquimia-dev/alquimia/alquimia_util.c:198:21: error: assignment makes pointer from integer without a cast
   destination->name = strdup(source->name);
                     ^
/media/data2/smolins/test1/alquimia-dev/alquimia/alquimia_util.c: In function ‘CopyAlquimiaAqueousConstraint’:
/media/data2/smolins/test1/alquimia-dev/alquimia/alquimia_util.c:220:37: error: assignment makes pointer from integer without a cast
   destination->primary_species_name = strdup(source->primary_species_name);
                                     ^
/media/data2/smolins/test1/alquimia-dev/alquimia/alquimia_util.c:223:32: error: assignment makes pointer from integer without a cast
   destination->constraint_type = strdup(source->constraint_type);
                                ^
/media/data2/smolins/test1/alquimia-dev/alquimia/alquimia_util.c:226:35: error: assignment makes pointer from integer without a cast
   destination->associated_species = strdup(source->associated_species);
                                   ^
/media/data2/smolins/test1/alquimia-dev/alquimia/alquimia_util.c: In function ‘CopyAlquimiaMineralConstraint’:
/media/data2/smolins/test1/alquimia-dev/alquimia/alquimia_util.c:247:29: error: assignment makes pointer from integer without a cast
   destination->mineral_name = strdup(source->mineral_name);
                             ^
make[2]: *** [alquimia/CMakeFiles/alquimia.dir/alquimia_util.c.o] Error 1
make[1]: *** [alquimia/CMakeFiles/alquimia.dir/all] Error 2
make: *** [all] Error 2

**Comment by jnjohnsonlbl** [comment]
Ahhhh, I thought this might be an issue, but I thought I could get away with it. I will fix.

Don’t forget Lara Kueppers’s Dynamic Vegetation meeting is starting soon.

Jeff

**Comment by smolins** [comment]
'make test' hangs up in test 14:

[...]
      Start 13: calcite_short_ac_crunch
13/24 Test #13: calcite_short_ac_crunch ..............   Passed    0.15 sec
      Start 14: calcite_short_cc_crunch

**Comment by jnjohnsonlbl** [comment]
I see that too on U67. Not on my Mac, though. Will investigate.

Jeff

**Comment by jnjohnsonlbl** [comment]
It's strange. Sometimes it hangs on the first Crunch test, sometimes the second. Always in CTest, sometimes when invoked from the command line (but usually not!), and never within GDB.

**Comment by jnjohnsonlbl** [comment]
On U67 only, I am seeing a HUGE memory allocation that seems to want to take all available memory on the machine. I am trying to figure out which allocation it is so I can fix it.

**Comment by smolins** [comment]
Does this memory allocation come from CrunchFlow? One thing that is left to
do for the crunchflow interface is to deallocate some variables, but that
would be at the end of the simulation.
Thanks

**Pull request closed without merging**
